version: '3'
services:
  node:
    build: .
    image: javascript-node
    container_name: node
    volumes:
      - ..:/workspace:delegated
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    restart: on-failure
volumes:
  node_modules:
